#!/usr/bin/env perl

use strict;
use warnings;
use Data::Dumper;
use Getopt::Long;
use Scalar::Util qw(looks_like_number);
use POSIX "strftime";

# variables {{{
my $_key = '';
my $_print = 0;
my $_list = 0;
my $_set = 0;
my $_help = 0;
my $file_gpg_yml = $ENV{'HOME'}."/.gnupg/gpg.yml";
# }}}

# logger {{{
sub log_print {

	# get log location
	my ($package, $filename, $line) = caller();
	my ($level, $message) = @_;
	$filename = substr($filename, rindex($filename, '/') + 1);

	my $current_date = strftime("%Y-%-m-%d %H:%M:%S", localtime);

	my $log_level;
	my $log_color;
	my $log_name;

	unless ($level) {
		return;
	}

	# log info and color
	if ($level eq 2) {
			$log_level = 2;
			$log_name = "debug";
	} elsif ($level eq 3) {
			$log_level = 3;
			$log_name = "warn";
	} elsif ($level eq 4) {
			$log_level = 4;
			$log_name = "error";
	} else {
			$log_level = 1;
			$log_name = "info";
	}

	# log style
	if ($log_level eq 4) {
		die("$current_date $filename :[$line]: $line $message\n");
	} elsif ($log_level eq 3) {
		warn("$current_date $filename :[$line]: $message\n");
	} elsif ($log_level eq 2) {
		print("$message\n");
	} elsif ($log_level eq 1) {
		print("$message");
	} else {
		print("$current_date $filename $message\n");
	}

}
# }}}

# argument parsing {{{
GetOptions(
    'p|print'      => \$_print,
    'h|help'       => \$_help,
) or die "Error in command line arguments. Use -h for help.\n";
# }}}

# yaml file {{{
sub file_generate {
    my @gpg_keys;
    my %current;
    my @users;
    my $state = '';
    open my $YData, '-|', 'gpg --list-secret-keys' or die "Can't run gpg: $!";
    while (<$YData>) {
        chomp;
        # Start of new key block
        if (/^sec\s+(\w+)\s+(\d{4}-\d{2}-\d{2})\s+\[SC\](?:\s+\[expires:\s+(\d{4}-\d{2}-\d{2})\])?/) {
            push @gpg_keys, { %current, users => [@users] } if %current;
            %current = (
                create => $2,
                algo   => $1,
                expire => $3 // '',
            );
            @users = ();
            $state = 'sec';
        }

        # Fingerprint
        elsif (/^\s+([A-F0-9]{40})$/) {
            $current{key} = $1;
        }

        # UID line
        elsif (/^uid\s+\[[^\]]+\]\s+(.*?)\s+<(.+?)>/) {
            my ($name, $mail) = ($1, $2);
            my ($sig) = /uid\s+\[([^\]]+)\]/;
            push @users, {
                name => $name,
                mail => $mail,
                sig  => $sig,
            };
        }

        # End of block when ssb is encountered
        elsif (/^ssb\s+(\w+)/) {
            $state = 'ssb';
        }
    }
    close $YData;
    push @gpg_keys, { %current, users => [@users] } if %current;

    # make sure that we have a yaml file
    unless (-e $file_gpg_yml) {
        $_print = 1;
    }

    if ($_print) {
        open(YFile, ">", $file_gpg_yml);
        print(YFile "gpg:\n");
        for my $key (@gpg_keys) {
            $key->{key} =~ s/^\s+|\s+$//g;
            $key->{create} =~ s/^\s+|\s+$//g;
            $key->{expire} =~ s/^\s+|\s+$//g;
            $key->{algo} =~ s/^\s+|\s+$//g;
            print(YFile "- key: '$key->{key}'\n");
            print(YFile "  create: '$key->{create}'\n");
            print(YFile "  expire: '$key->{expire}'\n") if $key->{expire};
            print(YFile "  algo: '$key->{algo}'\n");
            print(YFile "  users:\n");
            for my $user (@{ $key->{users} }) {
                $user->{name} =~ s/^\s+|\s+$//g;
                $user->{mail} =~ s/^\s+|\s+$//g;
                $user->{sig} =~ s/^\s+|\s+$//g;
                print(YFile "    - name: '$user->{name}'\n");
                print(YFile "      mail: '$user->{mail}'\n");
                print(YFile "      sig: '$user->{sig}'\n");
            }
        }
        close(YFile);
        log_print(3, "YAML file generated: ${file_gpg_yml}");
    }

    for my $key (@gpg_keys) {
        $key->{key} =~ s/^\s+|\s+$//g;
        $key->{create} =~ s/^\s+|\s+$//g;
        $key->{expire} =~ s/^\s+|\s+$//g;
        $key->{algo} =~ s/^\s+|\s+$//g;
        print(STDERR "- key: '$key->{key}'\n");
        print(STDERR "  create: '$key->{create}'\n");
        print(STDERR "  expire: '$key->{expire}'\n") if $key->{expire};
        print(STDERR "  algo: '$key->{algo}'\n");
        print(STDERR "  users:\n");
        for my $user (@{ $key->{users} }) {
            $user->{name} =~ s/^\s+|\s+$//g;
            $user->{mail} =~ s/^\s+|\s+$//g;
            $user->{sig} =~ s/^\s+|\s+$//g;
            print(STDERR "    - name: '$user->{name}'\n");
            print(STDERR "      mail: '$user->{mail}'\n");
            print(STDERR "      sig: '$user->{sig}'\n");
        }
    }
}

# }}}

file_generate();

my %current;
my @users;
my $state = '';

# apply settings {{{
sub git_apply {
    my $key = $_[0];
    my $name = $_[1];
    my $email = $_[2];
    my $commit = "~/.config/git/message-plain.txt";

    my $cmd_key = "git config user.signingkey '$key'";
    my $cmd_name = "git config user.name '$name'";
    my $cmd_email = "git config user.email '$email'";
    my $cmd_template = "git config user.email '$commit'";

    if ($cmd_email =~ 'sinacomsys' || $cmd_email =~ 'hesmailzadeh95') {
        $commit = "~/.config/git/message-sina.txt";
        $cmd_template = "git config commit.template '$commit'";
    }

    my $cmd_commit = "git config commit.template '$commit'";

    log_print(2, "$cmd_key");
    log_print(2, "$cmd_name");
    log_print(2, "$cmd_email");
    log_print(2, "$cmd_commit");

    system("$cmd_key");
    system("$cmd_name");
    system("$cmd_email");
    system("$cmd_commit");

}
# }}}

